export const SET_RECIPES = "SET_RECIPES";
export const SET_EDITING = "SET_EDITING";
export const SET_SELECTED_RECIPE = "SET_SELECTED_RECIPE";
export const SET_EDITING_RECIPE = "SET_EDITING_RECIPE";
export const SET_DELETE_MODAL = "SET_DELETE_MODAL";
